---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: sock-shop
spec:
  rules:
  - host: pavle9.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
  defaultBackend:
    service:
      name: front-end
      port:
        number: 80