name: deploy-test

on:
  push:
    branches:
    - "*"  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "t2-plan"
          service_account_key: /home/psarenac/actions-runner/gcp_key.json
          export_default_credentials: true

      - name: Install kubectl
        run: gcloud components install kubectl --quiet

      - name: Authenticate with GKE Cluster
        run: gcloud container clusters get-credentials pavle-cluster --region=us-central1 --zone=us-central1-a --project=t2-plan

      - name: Deploy Application to GKE
        run: |
          kubectl apply -f deploy/kubernetes/complete-demo.yaml
          until [ "$(kubectl get pods -n sock-shop --no-headers | grep -cEv '([0-9]+)/\1')" -eq 0 ]; do
              sleep 5s
              kubectl get pods -n sock-shop
              kubectl describe node | grep "Allocated resources" -A 10
          done
          kubectl get pod -A